### ISSUE TITLE
Party list needs updating

### ISSUE THREAD

**Issue by Floppy** [DemocracyClub/ge2015-election-data#4]

**Comment by symroe** [comment]
This list should be up to date:

http://openelectoralcommission.org.uk/parties/index.json

Or the CSV from YNMP will have all the parties of people actually standing:

https://edit.yournextmp.com/media/candidates.csv

**Comment by Floppy** [comment]
Excellent!

**Comment by philipjohn** [comment]
Done in [fd72c64] and there's now a conversion script for JSON > CSV in [5471255]
