### ISSUE TITLE
Commas in CSV are not escaped or quoted

### ISSUE THREAD

**Issue by DRMacIver** [DemocracyClub/ge2015-election-data#7]
See e.g. https://github.com/DemocracyClub/ge2015-election-data/blob/master/votes/horsham-votes.csv where you have the "The Peace Party - Non-violence, Justice, Environment" causing problems.

**Comment by philipjohn** [comment]
This should be fixed by #8 but that's pending some Travis fixing

**Comment by philipjohn** [comment]
Yep, fixed by #8
